### ISSUE TITLE
improve tlog client error handling

### ISSUE THREAD

**Issue by iwanbk** [g8os/blockstor#126]
In these parts:
- tlog client internal
- in nbdserver (better to wait for #106)

task list
- [x] tlogclient - recreate tcp connection in case of error (#156)
- [x] nbdserver - re-send the tlog if doesn't get response or response says error (#162)
- [x] nbdserver  - only Flush the operation after it get Flushed by tlog (#153)

**Comment by GlenDC** [comment]
We should make sure the TCP connection can be recreated in case the pipe was broken due to a disconnect, which can happen if the server was temporary unavailable. This kind of disconnect has to be detected.

On top of that we also need to make sure that we don't just throw away content that couldn't be send to the server. I think it makes sense if we could cache this within the client, as it would have already processed the content ready to be sent, meaning we would be able to just cache that content. Not sure yet how this would impact the API to make this type of behavior clear though.

**Comment by iwanbk** [comment]
I added tasks list to the issue description

**Comment by iwanbk** [comment]
>   it would have already processed the content ready to be sent, meaning we would be able to just cache that content

It is not valid anymore, because the capnp is encoded directly to the socket now.

>  Not sure yet how this would impact the API to make this type of behavior clear though.

yep

**Comment by iwanbk** [comment]
I think it doesn't matter that the client doesn't have processed content anymore, as the error hopefully happen rarely.

As for the API:
- we can specify timeout and max number of retry we want to do.
- change 'RecvOne' func to private func. As it is hard to use it properly anyway.

For this to work, we need #143 to be implemented.

**Comment by iwanbk** [comment]
> we can specify timeout and max number of retry we want to do

And what nbdserver need to do if it still failed after retrying? I think nbdserver should stop this vdisk because otherwise tlog won't contain valid logs.

**Comment by GlenDC** [comment]
> I think nbdserver should stop this vdisk because otherwise tlog won't contain valid logs.

Makes sense, only if the tlog is critical to the blockstor system. Is that always so? If that is indeed a critical piece of ANY type of vdisk, than we should indeed do that.

@robvanmieghem is a valid tlog chain a requirement for all types of vdisks?

**Comment by GlenDC** [comment]
> change 'RecvOne' func to private func. As it is hard to use it properly anyway.

I agee @iwanbk, going to make an issue for it.

**Comment by robvanmieghem** [comment]
@GlenDC @iwanbk 

> And what nbdserver need to do if it still failed after retrying? I think nbdserver should stop this vdisk because otherwise tlog won't contain valid logs.

Agreed

**Comment by GlenDC** [comment]
> And what nbdserver need to do if it still failed after retrying? I think nbdserver should stop this vdisk because otherwise tlog won't contain valid logs.

> > Agreed

Yes, since PR #203, I shut down the vdisk as soon as there is a fatal error related to the tlog stuff. And the content only gets written to the vdisk in case the tlog server has confirmed that the tlogs are flushed (and thus stored).
